### ISSUE TITLE
Can't seem to run in local

### ISSUE THREAD

**Issue by about-hector** [dillionverma/llm.report#11]
Hey, 

I did try running your website locally by filling all the fields of the .env.local file.
It seems however that something is wrong, the posthog api key is not considered valid (i am not authorized) and I don't get if it's because I'm missing some flags in my posthog project or what

also it's not clear to me what the withlogging.com website has to do with you, how the api behind it works etc. 
I can't find it in the code so I don't understand what happens exactly when I fetch a completion by using your domain rather than the original openai one.

would you mind guiding me on how to use all the features of your saas in a local environment for testing purposes?

**Comment by dillionverma** [comment]
Hey @about-hector thanks for pointing this out!

I'm working on improving self-hosted docs atm. Linked the PR to track progress.

**Comment by dillionverma** [comment]
Merged in PR, try now and let me know!

going to close issue as well

**Comment by lili21** [comment]
```bash
yarn dx
yarn run v1.22.11
$ run-s db:up db:setup dev
$ docker compose up -d || docker-compose up -d
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
[+] Running 1/1
 ⠿ llmreport_default_database_1  Restarted                                                                   0.5s
$ run-s db:deploy db:seed
$ npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "llm_report", schema "public" at "localhost:5432"

Error: P1001: Can't reach database server at `localhost`:`5432`

Please make sure your database server is running at `localhost`:`5432`.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "db:deploy" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "db:setup" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
