### ISSUE TITLE
[bug] Accessing the llm.report website encountered an error

### ISSUE THREAD

**Issue by zuobiao-zhou** [dillionverma/llm.report#48]
![image](https://github.com/dillionverma/llm.report/assets/61108539/3c3dc1a2-cfdc-4e21-af6e-3e4d5fccd630)
When I enter the sess-key, I do not get the expected page.

**Comment by dillionverma** [comment]
hi! thanks for reporting this :) 

Unfortunately, this project is no longer maintained and I don't have the resources at present to investigate what's going on. 

Really sorry about that!
